name: Deploy to Impresilk1

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Impresilk1
        uses: SamKirkland/FTP-Deploy-Action@4.1.2
        with:
          ftp-server: ftp.impresilk1.hospedagemdesites.ws
          ftp-username: impresilk1
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          ftp-port: 21
          local-dir: .
          server-dir: /home/impresilk1/impresilk
